spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:13388/./chacheexample;
      driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true